name = "onetruetool-shop"
main = "src/index.ts"
compatibility_date = "2025-03-09"
compatibility_flags = ["nodejs_compat"]

[[containers]]
class_name = "ShopContainer"
image = "./../../shop/Dockerfile"
max_instances = 1

[[durable_objects.bindings]]
class_name = "ShopContainer"
name = "SHOP_CONTAINER"

[[migrations]]
new_sqlite_classes = ["ShopContainer"]
tag = "v1"

[observability.logs]
enabled = true
invocation_logs = true
